
apiVersion: v1
kind: Service
metadata:
  name: l1-troubleshooting-service
  namespace: l1-app
spec:
  selector:
    app: l1-troubleshooting
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: ClusterIP
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: l1-troubleshooting-route
  namespace: l1-app
spec:
  to:
    kind: Service
    name: l1-troubleshooting-service
  port:
    targetPort: 5000
  tls:
    termination: edge
